<a href="https://colab.research.google.com/github/HunterTzou/DATA_110_FALL_2025/blob/main/week-01/Data201_Class1_Student.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Class 1 – Python Foundations (Student Notebook)

Bridge goal: translate familiar R patterns into Python.

Class 1 (Student Version): Python Fundamentals for R Users
Course: Intro to Data Analysis in Python
Background assumed: R, linear/logistic regression, basic ggplot2


=====================================================
 HOW TO USE THIS NOTEBOOK
=====================================================
 - Run cells top to bottom
 - Read the comments carefully
 - Complete all TODO sections
 - Predict outputs BEFORE running when prompted

=====================================================
 0. Setup
 =====================================================

In [8]:
import numpy as np
import pandas as pd

In [9]:
famous_quote = '"You have to be realistic about these things"'
print ("Here is a quote everyone who has read the series will recognize,",famous_quote)

Here is a quote everyone who has read the series will recognize, "You have to be realistic about these things"


 =====================================================
 1. First Contact: Python vs R
 =====================================================

 In R:
 x <- c(1, 2, 3)
 mean(x)

 In Python, we must say WHICH library computes the mean.

In [10]:
x = [1, 2, 3]

**Exercise**
1. Try np.mean(x)
2. What happens if you try mean(x)?

In [37]:
#Try np.mean(x)
np.mean(x)

np.float64(2.5)

In [38]:
#What happens if you try mean(x)?
mean(x)

NameError: name 'mean' is not defined

Type your response to question 2 here.

# 2. Objects, Types, and Explicitness

In [13]:
x_int = 3
x_float = 3.0
x_bool = True
x_none = None

**Exercise:**
Use type() to check the type of each object above.

In [39]:
#Type your code here.
type(x_int)
type(x_float)
type(x_bool)
type(x_none)

NoneType

 **Question:**
Which of these behaves most like NA in R? Which does NOT?

Answer:

I would say that finding the type of variable is closest to using R. The mean is similar, but in R, we are able to find the mean using base R with no libraries.

# 3. Core Data Structures

**A. Lists** (similar to flexible R lists)

In [42]:
L = [1, 2, 3, 4]

**Exercise**
1. Access the first element of L
2. Access the last element of L


Predict before running:
What will L[1:3] return?

In [40]:
#1.  Access the first element of L

L[0]

1

In [43]:
#2. Access the last element of L
L[3]

4

In [44]:
#What will L[1:3] return?
## It will return the second and third elements [2,3]
## The last element of the reference is always excluded

**B. Tuples** (immutable lists) ---

In [19]:
T = (1, 2, 3)

**Question:**
Why might immutability be useful?

- It could be useful because you might accidentally overwrite something in your code and you might want to keep that reference intact. Kind of like when you use the `$` sign in excel.

**C. Dictionaries** (named structures)


In [20]:
D = {"a": 10, "b": 20, "c": 30}

**Exercise**


In [45]:
# Extract the value associated with key "b"

D["b"]

20

# 4. Control Flow


In [50]:
x = 5

**A. If/elif/else statements**

**Exercise**
Write an if/elif/else statement that sets:


sign = "positive", "negative", or "zero"

In [51]:
#Write your if/elif/else statement

if x > 0:
  sign = "positive"
elif x < 0:
  sign = "negative"
else:
  sign = "zero"

print(sign)

positive


**B. For loops**

**Exercise**
Use a for-loop to create a list of squares from 0 to 4

In [52]:
#For-loop

for i in range(5):
  print(i**2)

0
1
4
9
16


** C. List comprehension** (Pythonic shortcut)

**Exercise**
Rewrite the previous loop using a list comprehension

In [25]:
#List comprehension

[i**2 for i in range(5)]

# 5. NumPy: Vectorized Computation

In [53]:
x = np.array([1, 2, 3, 4])
y = np.array([10, 20, 30, 40])

Predict BEFORE running:
What do you expect x + y to return?


**Exercise**

In [54]:
# 1. Compute x + y

x+y

array([11, 22, 33, 44])

In [55]:
# 2. Compute x * y

x*y

array([ 10,  40,  90, 160])

In [65]:
# 3. Add 5 to every element of x
## I had to put the expression 'int()' because we were getting the type along with the number like this: [np.int64(6), np.int64(7), np.int64(8), np.int64(9)]
for_loop = [int(i+5) for i in x]
print(for_loop)

[6, 7, 8, 9]


In [66]:
# 4. Compute the mean and standard deviation of x

print(np.mean(x))
print(np.std(x))

2.5
1.118033988749895


 Conditional logic (like ifelse in R)

**Exercise**

In [67]:
# Use np.where to return x when x > 2, and 0 otherwise

np.where(x > 2, x, 0)

array([0, 0, 3, 4])

# 6. Common Pitfalls for R Users


In [69]:
L = [1, 2, 3]

Predict:  
What will happen if you try L + 1?


**Exercise**

Try it and explain the result

---

I guess because it is a list, we cannot add values to the list? I guess because there are multiple items in a list, so the program does not know which one to add 1 to?

In [71]:
#Try L + 1

# L + 1 # This causes the TypeError
# To add 1 to each element, use a list comprehension:
result_list = [item + 1 for item in L]
print(result_list)

[2, 3, 4]


# 7. Active Learning Exercise (15–20 minutes)

 R code:
` x <- c(2, 4, 6, 8)`

` y <- ifelse(x > 4, x / 2, x * 2)`

 `mean(y)`


**TASK:**
1. Translate the code above into Python
2. Predict the value of y BEFORE computing
3. Compute mean(y)


In [85]:
# Step 1: Create x
x = np.array([2, 4, 6, 8])

In [87]:
# Step 2: Create y using NumPy
y = np.where(x > 4, x / 2, x * 2)
print(y)

[4. 8. 3. 4.]


In [90]:
# Step 3: Compute mean(y)

float(np.mean(y))

4.75

# 8. Wrap-Up Reflection

In 2–3 sentences:
 - What felt most different from R?
 - What felt familiar?
 - What questions do you still have?

 It seems that there are a lot less explicit math and computational functions in base python than in R. That makes sense considering that R was meant specifically for data science and analysis, where as Python is more of a general use language. I think that a lot of the functions are the same, but we need to explicitly use a library to get those functions. The nice part of this is that it is very customizable and we only have what we need.

 I am curious to see what other functions are different and if one can be said to be truly "better than the other" for data science or if they are just different ways of doing the same thing.